### PR TITLE
Add support to not collate report files

### PR DESCRIPTION
**Pull request by lyndsey-ferguson**
### Checklist
- [x] I've run `bundle exec rake` from the root directory to see all new and existing tests pass
- [x] I've read the [Contribution Guidelines][contributing doc]
- [x] I've updated the documentation if necessary.

### Motivation and Context

Adds support to **not** collate report files for people who want to use the intermediate report files for tools such as `xchtmlreport`.

Addresses [Feature Request: add option to NOT collate reports](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/95) and [Parallelization Bug: only the last completed test run block's tests are reported .test_result bundle](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues/107)

### Description

Will not collate reports per test run, nor will collate reports after completion of all batches of test runs.

[contributing doc]: ../docs/CONTRIBUTING.md

### CODE REVIEW

**Comment by lyndsey-ferguson** [comment]
Can you modify your `Pluginfile` per my instructions below, run `bundle install`, modify your call to `multi_scan` to include `collate_reports: false`, and then run your fastlane again?

Pluginfile:
```
gem 'fastlane-plugin-test_center', :git => "https://github.com/lyndsey-ferguson/fastlane-plugin-test_center.git", :branch => "issue-107-collation-optional"
```

Please attach the console output as a text file to this issue (makes it easier for me to review).

**Comment by lyndsey-ferguson** [comment]
You should be able to use `Dir.glob("#{your_output_directory}/**/*.test_result")` to grab an array of `test_result` bundles to pass to `xchtmlreport`.

**Comment by lyndsey-ferguson** [comment]
Tagging @ishammoho and @szymon-kazmierczak for better visibility.

**Comment by szymon-kazmierczak** [comment]
running the tests now 🤞

**Comment by szymon-kazmierczak** [comment]
Is it normal that there is a test_result within a test_result? The dir structure is:

SCHEME-batch-1/SCHEME-1.test_result/SCHEME.test_result 

I tried collating the reports using xchtmlreport and providing all 4 batches, but the initial ran of a batch wasn't included (there were 2 runs in one of the batches, first one had failures). 

I'm rerunning now and getting logs.

**Comment by lyndsey-ferguson** [comment]
@szymon-kazmierczak writes:
> Is it normal that there is a test_result within a test_result? The dir structure is:

No, I think that there is a problem with how I am "renaming" the test result directory.

**Comment by szymon-kazmierczak** [comment]
Ah I guess that would explain why the initial batch wasn't added to the final report 🤔

**Comment by lyndsey-ferguson** [comment]
> Ah I guess that would explain why the initial batch wasn't added to the final report 🤔

No, I think the way I've decided to collate the bundles is the cause of that. Previously tested tests get their own plist element in the collated result. 

https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/lib/fastlane/plugin/test_center/actions/collate_test_result_bundles.rb#L84

**Comment by lyndsey-ferguson** [comment]
@szymon-kazmierczak please remove your `Gemfile.lock` file, re-run `bundle install` and run your fastlane with `multi_scan` again. You should see multiple `test_result` bundles in each batch folder for each run of a batch of tests.

**Comment by ishammoho** [comment]
Perfect. it creates seperate bundles for each batch. Are you planning to collate them to one or plan is to leave as is? Thanks @lyndsey-ferguson

**Comment by lyndsey-ferguson** [comment]
@ishammoho It is up to you if you want to collate them or not. 

`multi_scan` will collate the `test_result` bundles as the default. It will have the option to to turn it off in case that the collation doesn't _quite_ work with `xchtmlreport` or any other external tool that people choose to use.

Now that I have added this feature, and at the same time, fixed collation, you can try and use the collated `test_result` to see if if works for you. Let me know if it does.

Thanks for testing and confirming!

**Comment by ishammoho** [comment]
Thanks @lyndsey-ferguson Collated test_results still shows results for last run batch.

**Pull request merged**
