### PR TITLE
Issue-164 new collate_xcresults action

### PR DESCRIPTION
**Pull request by lyndsey-ferguson**
### Checklist
- [x] I've run `bundle exec rake` from the root directory to see all new and existing tests pass
- [x] I've read the [Contribution Guidelines][contributing doc]
- [x] I've updated the documentation if necessary.

### Motivation and Context

With Xcode 11, the new output format is the `xcresult` bundle format. Fastlane's `scan` tool still is requesting a `result_bundle` file for the `xcodebuild` tool, which ends up becoming a symbolic link to the resultant `xcresult` bundle.

These bundles are no longer being collated correctly and data is now being lost.

### Description

1. Add an action that can use the underlying xcresult collation command line tool to merge xcresult files.
2. Update the multi_scan to handle xcresult files and to stop scan from trying to handle the output in an incorrect way.

[contributing doc]: ../docs/CONTRIBUTING.md

### CODE REVIEW

**Comment by lyndsey-ferguson** [comment]
Ok, so I've discovered a new twist in this feature request. With Xcode 11, the `test_results` that `scan` gets back from `xcodebuild` is actually an _alias_ to the `xcresult` folder.

So, in reality when a test run is complete, the `xcresult` is the source of truth.

When collating xcresult files, we should no longer collate test result bundles as that is wasted effort and invalid.

In a sense, can the entire collate test results bundle action be considered deprecated if using Xcode 11?

Does that mean `multi_scan` can issue a warning to the user that test results no longer work and that the user should specify xcresult in the output_types? And if test_result is given, we switch it to the xcresult of our choice?

Do we want to continue providing the user with a test_result alias?

So, in summary:
1. When in Xcode 11
    1. set a process variable indicating what the version of xcode is (if it doesn't already exist in multi_scan or scan)
    1. issue a warning when the user requests test_results that we will turn on xcresults for them.
    1. turn off xcresults for them. Look for other report names and use one of them. If there are no report names. use the default report name.
    1. in retrying_scan_helper, make sure that the options for xcargs is using our testResultBundlePath with the xcresult file extension
    1. in the retrying_scan_helper, exit out of the code that collates test result bundles
    1. when done collating everything, create a test_result alias to the xcresult file? That seems stupid. But it could prevent `multi_scan` from breaking people's code that relies on it, and there is no reason not to provide this to users.
    1. in the summary, do not look for any test result bundles.

Okay, sounds good? Great!

**Comment by lyndsey-ferguson** [comment]
@jineshqa, I have a functional ability to collate xcresult files. Can you modify your `Pluginfile` per my instructions below, run `bundle install`, and then run your fastlane again (with the `--verbose` flag)?

Pluginfile:
```
gem 'fastlane-plugin-test_center', :git => "https://github.com/lyndsey-ferguson/fastlane-plugin-test_center.git", :branch => "BRANCHNAME"
```

Once you do that, you can continue passing `result_bundle: true` **OR** you can remove that and add the `xcresult` format to your `output_types` parameter (I still have to update the documentation).

If there are still problems, please let me know and attach the console output as a text file to this issue (makes it easier for me to review).  If it works, please let me know.

**Comment by NordicBat** [comment]
Hi @lyndsey-ferguson I just tried as you instructed @jineshqa on the prior comments.
For me, at least, it worked 🎉 
Definitely going to test a little more, but still, thank you for work

**Comment by lyndsey-ferguson** [comment]
@NordicBat fantastic.

I did find one issue on my end, if your xcresult path has a space in it, the xcmergetool will crash.

**Comment by jineshqa** [comment]
@lyndsey-ferguson Apologies for not responding. Dealing with some family things, will get back to you as soon as I can.

**Comment by lyndsey-ferguson** [comment]
I've fixed the issue where xcresulttool crashes with spaces in file paths.

Pluginfile:
```
gem 'fastlane-plugin-test_center', '3.9.0.beta.2'
```

Once you do that, you can continue passing `result_bundle: true` **OR** you can remove that and add the `xcresult` format to your `output_types` parameter (I still have to update the documentation).

If there are still problems, please let me know and attach the console output as a text file to this issue (makes it easier for me to review).  If it works, please let me know.

**Pull request merged**
