### PR TITLE
issue-35 Improved README

### PR DESCRIPTION
**Pull request by lyndsey-ferguson**
##### Description

[WIP] Address Issue #35 by cleaning up the plugin's README. This will add:
- [ ] a project banner
- [x] an elevator pitch
- [x] an animated example
- [x] the example script for dev's to put into production right away
- [x] a table-of-contents
- [x] docs for installation
- [x] docs for overview
- [x] docs for actions and examples
- [ ] instructions on how to contribute.

### CODE REVIEW

**Comment by lyndsey-ferguson** [comment]
@zacoid55, @gmgchow, @fishercraigj, @dionc, @armando-leal, @zanizrules, @Sandhu412, @szymon-kazmierczak, @lucasecf, @jcharr1, @kisialiu: would you mind looking at line 8 of the README? I want to provide paragraph that will be compelling and interesting to developers who visit the repo for the first time.

What do you think?

**Comment by szymon-kazmierczak** [comment]
I like the placeholder 😂My main use case for this plugin is the ability to rerun a test to verify whether its flaky or failing, I assume my tests are not flaky :)

**Comment by zacoid55** [comment]
I love it, that's absolutely what I'd describe this plugin as 💪

**Comment by lyndsey-ferguson** [comment]
@szymon-kazmierczak @zacoid55 what do you think of the example lane? Is it **too** long?

**Comment by szymon-kazmierczak** [comment]
Yeah, something simple to get people started. Then another sample (or a link to it) to show the capabilities of the plugin.

**Comment by lyndsey-ferguson** [comment]
@szymon-kazmierczak what do you think of this change based off of your feedback?

**Comment by szymon-kazmierczak** [comment]
Looks amazing :) 🎉

**Pull request merged**
