### PR TITLE
Improve plugin documentation

### PR DESCRIPTION
**Pull request by lyndsey-ferguson**
### Checklist
- [x] I've run `bundle exec rake` from the root directory to see all new and existing tests pass
- [x] I've read the [Contribution Guidelines][contributing doc]
- [x] I've updated the documentation if necessary.

### Motivation and Context

The README was becoming far too large, and, I suspect, intimidating. I simplified this and document the options that are available for each action.

### Description

[contributing doc]: ../docs/CONTRIBUTING.md

### CODE REVIEW

**Comment by lyndsey-ferguson** [comment]
@kisialiu  @zacoid55 @Sandhu412 @ishammoho @jineshqa @szymon-kazmierczak @rahulsharma2905 @hactar @sandipdhagdi  I'm improving the documentation for this plugin. If you have any feedback, I'm open to it.

**Comment by lyndsey-ferguson** [comment]
You can see how it looks in [markdown here](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/tree/improve-readme-3.0)

**Comment by jineshqa** [comment]
May be you could improve example of collate_test_result_bundles. 
1.  `bundles = Dir['../spec/fixtures/*.test_result'].map { |relpath| File.absolute_path(relpath) }` Sort bundles by time so the later bundles where test have passed overwrite the earlier where test have failed. I had to deal with that when merging Junit report from each bundle. Below is how I did it.
```
lane :collate_results do
    bundles = Dir['./test_output/*.xcresult'].sort_by{ |f| File.mtime(f) }
    bundles.each do |bundle|
      xcresulttool_cmd = 'trainer -p '
      xcresulttool_cmd += bundle + " -o ./test_output/"
      sh xcresulttool_cmd
    end
    reports_unsorted = Dir['./test_output/*.xml'].map { |relpath| File.absolute_path(relpath) }
    reports = reports_unsorted.sort_by{ |f| File.mtime(f) }
    collate_junit_reports(
      reports: reports,
      collated_report: File.join('./fastlane/test_output/', 'result.xml')
    )
end
```
2. `collated_bundle: File.join(Dir.mktmpdir, 'result.test_result')` here `Dir.mktmpdir` could be replaced with `./outputdir`

Just my suggestions, feel free to ignore them.

**Comment by Sanjaneya-chewy** [comment]
@lyndsey-ferguson -- I have been sidetracked into working on other non fastlane related stuff at work, so haven't been able to follow along as much. But my comments are inline with @jineshqa. May be if you could add a full example lane that uses all the collate reports, would be useful documentation. I am back to using fastlane now, so I will run the latest release on my new project and will get back to you if I find anything else. As always, thanks for this great plugin and all your efforts.

**Comment by Sandhu412** [comment]
@lyndsey-ferguson -- I have been sidetracked into working on other non fastlane related stuff at work, so haven't been able to follow along as much. But my comments are inline with @jineshqa. May be if you could add a full example lane that uses all the collate reports, would be useful documentation. I am back to using fastlane now, so I will run the latest release on my new project and will get back to you if I find anything else. As always, thanks for this great plugin and all your efforts.

**Pull request merged**
